Repository BHoM/LifeCycleAssessment_Toolkit, pull requests merged in 2020-04, with the labels that each got.

#70 Update ReadMe
  README.md
Labels: type:documentation

#74 Adjust ICE Datasets to match oM changes
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aggregates.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aluminum.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Asphalt.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Bitumen.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_CementMortar.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_ClayBricks.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Concrete.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Glass.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Steel.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberExcludingStorage.json
  DataSets/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberIncludingStorage.json
Labels: type:bug

#77 Add CQD Datasets and organise datasets folder
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseConcreteGeneric.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseConcreteNational.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseConcreteRegional.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseSteelDecking.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseSteelFraming.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseSteelReinforcing.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseSteelStuds.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseTimberFramingElements.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseTimberGlueLam.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseTimberLVL.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseTimberOSB.json
  DataSets/LifeCycleAssessment/CarbonQueryDatabase/CarbonQueryDatabaseTimberPlywood.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_ConcreteGeneric.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_ConcreteNational.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_ConcreteRegional.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_SteelDecking.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_SteelFraming.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_SteelReinforcing.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_SteelStuds.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_TimberFramingElements.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_TimberGlueLam.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_TimberLVL.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_TimberOSB.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_TimberPlywood.json
Labels: type:feature

#83 Add reference to Physical_oM
  LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
Labels: type:feature
