Repository BHoM/LifeCycleAssessment_Toolkit, pull requests merged in 2020-06, with the labels that each got.

#97 Update references and post build
  LifeCycleAssessment_Engine/LifeCycleAssessment_Engine.csproj
Labels: type:external-api-changes

#102 Added results in enclosure and foundation scope to results returned for LifeCycleAssessment Result
  LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessment.cs
Labels: type:bug

#112 ICE Datasets Update QuantityType
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aggregates.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aluminum.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Asphalt.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Bitumen.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_CementMortar.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_ClayBricks.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Concrete.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Glass.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Steel.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberExcludingStorage.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberIncludingStorage.json
Labels: type:bug

#113 Update Readme
  README.md
Labels: type:documentation

#116 EvalScope method multiplication of results fix
  LifeCycleAssessment_Engine/Compute/EvaluateLifeCycleAssessment.cs
Labels: type:bug

#117 NaN Density Values causing eval errors and missing error handling
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_LW_2501-3000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_LW_3001-4000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_LW_4001-5000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_0-2500.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_2501-3000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_3001-4000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_4001-5000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_5001-6000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Concrete_NW_6001-8000.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Steel.json
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Timber.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aggregates.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Aluminum.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Asphalt.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Bitumen.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_CementMortar.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_ClayBricks.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Concrete.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Glass.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_Steel.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberExcludingStorage.json
  DataSets/LifeCycleAssessment/InventoryOfCarbonAndEnergy/InventoryOfCarbonAndEnergy_TimberIncludingStorage.json
  DataSets/LifeCycleAssessment/QuartzElementData.json
  LifeCycleAssessment_Engine/Compute/EvaluateEnvironmentalProductDeclaration.cs
  LifeCycleAssessment_Engine/Query/GetFragmentDensity.cs
Labels: severity:critical, type:bug

#123 Change Metal decking QuantityType
  DataSets/LifeCycleAssessment/EmbodiedCarbonInConstructionCalculator/EC3_Steel.json
Labels: type:bug
